<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>DeltaForge.Tests.Adbc.Ingest</RootNamespace>
    <AssemblyName>TestAdbcIngest</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Apache.Arrow" Version="20.0.0" />
    <PackageReference Include="Apache.Arrow.Adbc" Version="0.18.0" />
  </ItemGroup>
</Project>
